# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow')], max_length=1)),
                ('project_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
