# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20171004_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='task_day',
            field=models.DateField(default=datetime.date(2017, 10, 5)),
        ),
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.TimeField(default=datetime.datetime(2017, 10, 5, 17, 33, 0, 374474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('DONE', 'Done Task'), ('NOTDONE', 'Not Done Task')], default='Not Done Task', max_length=7),
        ),
    ]
